included:
  - Sauron

disabled_rules:
  - trailing_whitespace
  - file_header

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

identifier_name:
  min_length: 2
  excluded:
    - id
    - r
    - g
    - b

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 600
  error: 1000

reporter: xcode
